### PR TITLE
Added info about the closest available park to the yellow or red parks

### PR DESCRIPTION
**Pull request by Obadable**
The algorithm calculates the closest park in a straight line. It does not take into account the route for an actual car.

Authors: Anas & Obada

### CODE REVIEW

**Comment by Obadable** [comment]
The conflict can be fixed by keeping both the code form this branch and the code from the master, I can resolve it as soon as this branch gets approved.

**Comment by jjuliamolin** [comment]
Does the code meet set acceptance criteria? NO
Conflicts with existing code? YES, but easy to solve.

Is all code well commented? NO

Is it possible to extend the code without having to rewrite a lot of code? YES

Do you understand the code? Yes

Other:
I don't really see the point of showing "the closest parking" to the user. In many cases, the closest one will be on the same street. for example on Gibraltargatan: "the closest is at gibraltargatan". 

I still think we can use all of the code, just change som things:
- instead of finding ONE parking, find 10(?). we can save it in an array/list which is prioritized on distance (if we push an 11th element, it will remove the longest one), after the loop we have the 10 most adjacent parkings. not sure of the best data structure for this in js.

- Take colors in to account, why suggest the closest parking if it isn't available? We can save all green parking in a list and only compare these when we suggest the closest parkings suggestion.


- I see this as a button "show adjacent parkings", and I think it could be on all markers (even green ones), since I guess there will be a common scenario when the user go to a green parking which is occupied. The pros with a button is also, that we don't need to calculate the closest parkings for every parking. We just do it for a specific parking when the button is clicked.


Even though I think we should change some things you did a great job! Lets discuss this tomorrow, how we want to use the function :)

**Review by swallson — APPROVED** [review]
Does the code meet set acceptance criteria? NO
Conflicts with existing code? apparently

Is all code well commented? NYEOS

Is it possible to extend the code without having to rewrite a lot of code? YES

Do you understand the code? YES

Other:
Good job!

**Comment by Obadable** [comment]
> Does the code meet set acceptance criteria? NO
> Conflicts with existing code? YES, but easy to solve.
> 
> Is all code well commented? NO
> 
> Is it possible to extend the code without having to rewrite a lot of code? YES
> 
> Do you understand the code? Yes
> 
> Other:
> I don't really see the point of showing "the closest parking" to the user. In many cases, the closest one will be on the same street. for example on Gibraltargatan: "the closest is at gibraltargatan".
> 
> I still think we can use all of the code, just change som things:
> 
> * instead of finding ONE parking, find 10(?). we can save it in an array/list which is prioritized on distance (if we push an 11th element, it will remove the longest one), after the loop we have the 10 most adjacent parkings. not sure of the best data structure for this in js.
> * Take colors in to account, why suggest the closest parking if it isn't available? We can save all green parking in a list and only compare these when we suggest the closest parkings suggestion.
> * I see this as a button "show adjacent parkings", and I think it could be on all markers (even green ones), since I guess there will be a common scenario when the user go to a green parking which is occupied. The pros with a button is also, that we don't need to calculate the closest parkings for every parking. We just do it for a specific parking when the button is clicked.
> 
> Even though I think we should change some things you did a great job! Lets discuss this tomorrow, how we want to use the function :)

Great! will be fixed in the next sprint :)

**Pull request merged**
